# Generated by Django 2.2.7 on 2019-11-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('house_number', models.IntegerField()),
                ('street_name', models.TextField()),
                ('apt_number', models.IntegerField(blank=True, null=True)),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip_code', models.IntegerField()),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminSiteCredentials',
            fields=[
                ('username', models.AutoField(primary_key=True, serialize=False)),
                ('salted_and_hashed_password', models.TextField()),
            ],
            options={
                'db_table': 'admin_site_credentials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistributionCenter',
            fields=[
                ('distribution_center_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'distribution_center',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('initial_estimated_arrival_date', models.DateTimeField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParcelType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_description', models.TextField()),
            ],
            options={
                'db_table': 'parcel_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingLeg',
            fields=[
                ('leg_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shipping_leg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransitHardAsset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.TextField()),
                ('model', models.TextField()),
                ('purchase_date', models.DateTimeField()),
                ('temperature_controlled', models.TextField()),
            ],
            options={
                'db_table': 'transit_hard_asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransitMethod',
            fields=[
                ('method_id', models.AutoField(primary_key=True, serialize=False)),
                ('method_description', models.TextField()),
            ],
            options={
                'db_table': 'transit_method',
                'managed': False,
            },
        ),
    ]
