# Generated by Django 2.2.7 on 2019-11-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.AlterModelOptions(
            name='adminsitecredentials',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='distributioncenter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parceltype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shippingleg',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transithardasset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transitmethod',
            options={},
        ),
    ]
