# Generated by Django 2.2.7 on 2019-11-30 23:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191127_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'db_table': 'admin_site_credentials',
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='AdminSiteCredentials',
        ),
    ]
