# Generated by Django 2.2.7 on 2019-11-30 23:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191130_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSiteCredentials',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.AutoField(primary_key=True, serialize=False)),
                ('salted_and_hashed_password', models.TextField()),
            ],
            options={
                'db_table': 'admin_site_credentials',
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
