# Generated by Django 2.2.7 on 2019-11-30 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191130_2332'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adminsitecredentials',
            managers=[
            ],
        ),
    ]
