# Generated by Django 2.2.7 on 2019-12-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191130_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transithardasset',
            name='temperature_controlled',
            field=models.BooleanField(),
        ),
    ]
