# Generated by Django 2.2.7 on 2019-12-02 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191201_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderParcelType',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('parcel_type', models.IntegerField()),
            ],
            options={
                'db_table': 'order_parcel_type',
            },
        ),
        migrations.CreateModel(
            name='ShipFromAddress',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ships_from_address',
            },
        ),
        migrations.CreateModel(
            name='ShipFromCustomer',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ships_from_customer',
            },
        ),
        migrations.CreateModel(
            name='ShipToAddress',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ships_to_address',
            },
        ),
        migrations.CreateModel(
            name='ShipToCustomer',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ships_to_customer',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(db_column='order_id', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='StatusUpdates',
            fields=[
                ('order', models.ForeignKey(db_column='order', default=1, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Order')),
                ('distribution_center', models.ForeignKey(db_column='distribution_center', on_delete=django.db.models.deletion.DO_NOTHING, to='api.DistributionCenter')),
                ('enter_leg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='enter_leg', to='api.ShippingLeg')),
                ('exit_leg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exit_leg', to='api.ShippingLeg')),
            ],
            options={
                'db_table': 'status_updates',
                'unique_together': {('order', 'distribution_center')},
            },
        ),
    ]
