# Generated by Django 2.2.7 on 2019-12-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191201_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderParcelType',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('parcel_type', models.IntegerField()),
            ],
            options={
                'db_table': 'order_parcel_type',
            },
        ),
        migrations.CreateModel(
            name='ShipFromAddress',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ships_from_address',
            },
        ),
        migrations.CreateModel(
            name='ShipFromCustomer',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ships_from_customer',
            },
        ),
        migrations.CreateModel(
            name='ShipToAddress',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ships_to_address',
            },
        ),
        migrations.CreateModel(
            name='ShipToCustomer',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ships_to_customer',
            },
        ),
    ]
