# Generated by Django 2.2.7 on 2019-12-02 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_orderparceltype_shipfromaddress_shipfromcustomer_shiptoaddress_shiptocustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusUpdates',
            fields=[
                ('status_update_id', models.AutoField(primary_key=True, serialize=False)),
                ('distribution_center', models.ForeignKey(db_column='distribution_center', on_delete=django.db.models.deletion.DO_NOTHING, to='api.DistributionCenter')),
                ('enter_leg', models.ForeignKey(db_column='enter_leg', on_delete=django.db.models.deletion.DO_NOTHING, related_name='enter_leg', to='api.ShippingLeg')),
                ('exit_leg', models.ForeignKey(db_column='exit_leg', on_delete=django.db.models.deletion.DO_NOTHING, related_name='exit_leg', to='api.ShippingLeg')),
                ('order', models.ForeignKey(db_column='order', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Order')),
            ],
            options={
                'db_table': 'status_updates',
                'unique_together': {('order', 'distribution_center')},
            },
        ),
    ]
