# Generated by Django 2.2.7 on 2019-12-02 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_statusupdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupdates',
            name='enter_leg',
            field=models.ForeignKey(blank=True, db_column='enter_leg', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enter_leg', to='api.ShippingLeg'),
        ),
        migrations.AlterField(
            model_name='statusupdates',
            name='exit_leg',
            field=models.ForeignKey(blank=True, db_column='exit_leg', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exit_leg', to='api.ShippingLeg'),
        ),
    ]
