# Generated by Django 2.2.7 on 2019-12-02 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191202_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusupdates',
            name='order_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Order'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='statusupdates',
            unique_together={('order_id', 'distribution_center')},
        ),
        migrations.RemoveField(
            model_name='statusupdates',
            name='order',
        ),
    ]
