# Generated by Django 2.2.7 on 2019-12-02 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191202_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupdates',
            name='order_id',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Order'),
        ),
    ]
