# Generated by Django 2.2.7 on 2019-12-02 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191202_1459'),
        ('api', '0008_auto_20191202_0221'),
    ]

    operations = [
    ]
