# Generated by Django 2.2.7 on 2019-12-02 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20191202_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusupdates',
            name='order_id',
            field=models.ForeignKey(db_column='order_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statusupdates',
            name='status_update_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statusupdates',
            name='enter_leg',
            field=models.ForeignKey(blank=True, db_column='enter_leg', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enter_leg', to='api.ShippingLeg'),
        ),
        migrations.AlterField(
            model_name='statusupdates',
            name='exit_leg',
            field=models.ForeignKey(blank=True, db_column='exit_leg', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exit_leg', to='api.ShippingLeg'),
        ),
        migrations.AlterUniqueTogether(
            name='statusupdates',
            unique_together={('order_id', 'distribution_center')},
        ),
        migrations.RemoveField(
            model_name='statusupdates',
            name='order',
        ),
    ]
