# Generated by Django 2.2.7 on 2019-12-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_shippingrates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrates',
            name='effective_date',
            field=models.DateField(),
        ),
    ]
