# Generated by Django 2.2.7 on 2019-12-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191202_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionCenterAddress',
            fields=[
                ('distribution_center_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address_id', models.IntegerField()),
            ],
            options={
                'db_table': 'distribution_center_address',
            },
        ),
    ]
