# Generated by Django 2.2.7 on 2019-12-03 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_distributioncenteraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributioncenteraddress',
            name='address_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Address'),
        ),
        migrations.AlterField(
            model_name='distributioncenteraddress',
            name='distribution_center_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.DistributionCenter'),
        ),
    ]
