# Generated by Django 2.2.7 on 2019-12-03 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191202_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributioncenteraddress',
            name='distribution_center_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.DistributionCenter'),
        ),
    ]
