# Generated by Django 2.2.7 on 2019-12-03 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191202_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingLegOrigin',
            fields=[
                ('shipping_leg_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.ShippingLeg')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Address')),
            ],
            options={
                'db_table': 'shipping_leg_origin',
            },
        ),
        migrations.CreateModel(
            name='ShippingLegDestination',
            fields=[
                ('shipping_leg_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.ShippingLeg')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Address')),
            ],
            options={
                'db_table': 'shipping_leg_destination',
            },
        ),
    ]
