# Generated by Django 2.2.7 on 2019-12-03 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_shippinglegdestination_shippinglegorigin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinglegdestination',
            name='shipping_leg_id',
            field=models.OneToOneField(db_column='shipping_leg_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.ShippingLeg'),
        ),
        migrations.AlterField(
            model_name='shippinglegorigin',
            name='shipping_leg_id',
            field=models.OneToOneField(db_column='shipping_leg_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.ShippingLeg'),
        ),
    ]
