# Generated by Django 2.2.7 on 2019-12-03 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20191202_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinglegdestination',
            name='address_id',
            field=models.ForeignKey(db_column='address_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Address'),
        ),
        migrations.AlterField(
            model_name='shippinglegorigin',
            name='address_id',
            field=models.ForeignKey(db_column='address_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Address'),
        ),
    ]
