# Generated by Django 2.2.7 on 2019-12-04 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_transitassetmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributioncenteraddress',
            name='distribution_center_id',
            field=models.OneToOneField(db_column='distribution_center_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.DistributionCenter'),
        ),
    ]
